//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Account
    {
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NguoiQuanLy NguoiQuanLy { get; set; }
    }
}
